# Generated by Django 4.1.4 on 2022-12-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('age_rating', models.CharField(max_length=100)),
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('showing_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('available_seats', models.IntegerField()),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.film')),
            ],
        ),
    ]
