# Generated by Django 4.1.3 on 2023-01-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showing',
            old_name='film_id',
            new_name='film',
        ),
    ]
