# Generated by Django 4.1.3 on 2023-01-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_film_id_showing_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
